Technical support/Models/Request.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace Technical_support.Models
{
    public class Request
    {
        // ID заявки
        [Key]
        [Required]
        public virtual int RequestId { get; set; }

        // ID Пользователя
        [Required]
        [DisplayName("ID Пользователя")]
        public virtual required string UserId { get; set; }
        public IdentityUser User { get; set; }

        // ID темы заявки
        [Required]
        [DisplayName("ID темы заявки")]
        public virtual int ThemeId { get; set; }
        public required ThemeRequest Theme { get; set; }

        // ID приоритета заявки
        [Required]
        [DisplayName("Приоритет заявки")]
        public virtual int PrioritetId { get; set; }
        public required Prioritet Prioritet { get; set; }

        [Required]
        [DisplayName("Текст заявки")]
        public virtual required string TextRequest { get; set; }


        [DisplayName("Файл")]
        public virtual byte[]? File { get; set; }
        [NotMapped]
        public virtual IFormFile? Image { get; set; }

        // Дата открытия заявки
        [Required]
        [DisplayName("Дата открытия заявки")]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yy}")]
        public virtual required DateTime DateOpen { get; set; }

        // ID закрепленного Сотрудника
        [DisplayName("ID Сотрудника")]
        public virtual string? ManagerId { get; set; }

        public IdentityUser Manager { get; set; }

        // Дата закрытия заявки
        [DisplayName("Дата закрытия заявки")]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yy}")]
        public virtual DateTime? DateClose { get; set; }

        // ID Состояния заявки
        [Required]
        [DisplayName("ID Состояния заявки")]
        public virtual int StatusRequestId { get; set; }
        public StatusRequest StatusRequest { get; set; }
    }
}

Technical support/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Technical_support.Data;
using Technical_support.Models;
using Technical_support.ViewModel;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Routing.Constraints;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;
using Azure.Core;
using Request = Technical_support.Models.Request;

namespace Technical_support.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public RequestsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _environment = hostEnvironment;
        }

        // Метод для получения заявок пользователя
        public IActionResult MyRequests(string id)
        {
            List<MyRequests> myList = new();
            foreach (var item in _context.Request)
            {
                string theme = "";
                string? managerName = "";
                string status = "";
                string prioritet = "";
                if (item.UserId == id)
                {
                    foreach (var item1 in _context.ThemeRequests)
                    {
                        if (item1.ThemeId == item.ThemeId)
                            theme = item1.NameTheme;
                    }
                    foreach (var item2 in _context.StatusRequests)
                    {
                        if (item2.StatusRequestId == item.StatusRequestId)
                            status = item2.Status;
                    }
                    foreach (var item3 in _context.Users)
                    {
                        if (item3.Id == item.ManagerId)
                            managerName = item3.UserName;
                    }
                    foreach (var item4 in _context.Prioritets)
                    {
                        if (item4.PrioritetId == item.PrioritetId)
                            prioritet = item4.PrioritetRequest;
                    }
                    myList.Add(new MyRequests
                    {
                        RequestId = item.RequestId,
                        Theme = theme,
                        Prioritet = prioritet,
                        TextRequest = item.TextRequest,
                        DateOpen = item.DateOpen,
                        ManagerName = managerName,
                        DateClose = item.DateClose,
                        StatusRequest = status,
                    });
                }
            }
            return View(myList);
        }


        //Метод для просмотра выбранной заявки
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Request == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .Include(r => r.Manager)
                .Include(r => r.User)
                .Include(r => r.StatusRequest)
                .Include(r => r.Theme)
                 .Include(r => r.Prioritet)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }
            List<Response> responses = _context.Responses
                           .Where(c => c.RequestId == id)
                           .ToList();
            RequestDetail requestDetail = new RequestDetail();
            requestDetail.Request = request;
            requestDetail.ListResponses = responses;
            return View(requestDetail);
        }

        // Метод для создания заявки GET
        public IActionResult Create()
        {
            ViewData["StatusRequestId"] = new SelectList(_context.StatusRequests, "StatusRequestId", "Status");
            ViewData["ThemeId"] = new SelectList(_context.ThemeRequests, "ThemeId", "DescriptionTheme");
            ViewData["PrioritetId"] = new SelectList(_context.Prioritets, "PrioritetId", "PrioritetRequest");
            return View();
        }

        // Метод для создания заявки POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequestId,UserId,ThemeId,PrioritetId,TextRequest,Image,DateOpen,ManagerId,DateClose,StatusRequestId")] Request request)
        {
            string filename = "";
            if (request.Image != null)
            {
                string uploadfolder = Path.Combine(_environment.WebRootPath, "images");
                filename = Guid.NewGuid().ToString() + "_" + request.Image.FileName;
                string filepath = Path.Combine(uploadfolder, filename);
                request.Image.CopyTo(new FileStream(filepath, FileMode.Create));
                byte[]? FileContent = null;
                if (request.Image.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        request.Image.CopyTo(ms);
                        FileContent = ms.ToArray();
                    }
                }
                request.File = FileContent;
            }
            string userId = request.UserId;
            request.DateOpen = DateTime.Now;
            ModelState.Remove("image");
            ModelState.Remove("DateOpen");
            ModelState.Remove("Manager");
            ModelState.Remove("User");
            ModelState.Remove("StatusRequest");
            ModelState.Remove("Theme");
            ModelState.Remove("Prioritet");
            if (ModelState.IsValid)
            {
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction("MyRequests", new RouteValueDictionary(new
                {
                    Controller = "Requests",
                    Action = "MyRequests",
                    id = userId
                }));
            }
            ViewData["StatusRequestId"] = new SelectList(_context.StatusRequests, "StatusRequestId", "Status", request.StatusRequestId);
            ViewData["ThemeId"] = new SelectList(_context.ThemeRequests, "ThemeId", "DescriptionTheme", request.ThemeId);
            ViewData["PrioritetId"] = new SelectList(_context.Prioritets, "PrioritetId", "PrioritetRequest");
            return View(request);
        }

        // Метод для редактирования заявки GET
        public async Task<IActionResult> Edit(string user, int id)
        {
            if (id == null || _context.Request == null)
            {
                return NotFound();
            }
            if (user == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            var managers = from role in _context.Roles
                           .Where(c => c.Name == "Manager" || c.Name == "Admin")
                           join roles in _context.UserRoles on role.Id equals roles.RoleId
                           join users in _context.Users on roles.UserId equals users.Id
                           select new
                           {
                               users.Id,
                               users.UserName
                           };
            ViewData["ManagerId"] = new SelectList(managers, "Id", "UserName", request.ManagerId);
            ViewData["StatusRequestId"] = new SelectList(_context.StatusRequests, "StatusRequestId", "Status", request.StatusRequestId);
            ViewData["ThemeId"] = new SelectList(_context.ThemeRequests, "ThemeId", "DescriptionTheme", request.ThemeId);
            ViewData["PrioritetId"] = new SelectList(_context.Prioritets, "PrioritetId", "PrioritetRequest");
            return View(request);
        }

        // Метод для редактирования заявки POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string user, int id, [Bind("RequestId,UserId,ThemeId,PrioritetId,TextRequest,Image,DateOpen,ManagerId,DateClose,StatusRequestId")] Request request)
        {
            if (id != request.RequestId)
            {
                return NotFound();
            }
            if (request.Image != null)
            {
                //string uploadfolder = Path.Combine(_environment.WebRootPath, "images");
                //filename = Guid.NewGuid().ToString() + "_" + request.Image.FileName;
                //string filepath = Path.Combine(uploadfolder, filename);
                //request.Image.CopyTo(new FileStream(filepath, FileMode.Create));
                byte[]? FileContent = null;
                if (request.Image.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        request.Image.CopyTo(ms);
                        FileContent = ms.ToArray();
                    }
                }
                request.File = FileContent;
            }
            string userId = request.UserId;
            if (request.StatusRequestId == 1 || request.StatusRequestId == 4)
            {
                request.ManagerId = null;
            }
            var responces = _context.Responses
                           .Where(c => c.RequestId == request.RequestId);
            int b = responces.Count();
            if (responces.Count() == 0 && request.StatusRequestId == 3) 

Technical support/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Technical_support.Data;
using Technical_support.Models;
using Response = Technical_support.Models.Response;

namespace Technical_support.Controllers
{
    public class ResponsesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResponsesController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Manager,Admin")]
        // GET: Responses/Create
        public IActionResult Create(int id)
        {
            ViewData["RequestId"] = id;
            var request = _context.Request.Find(id);
            ViewData["TextRequest"] = request.TextRequest;
            return View();
        }

        [Authorize(Roles = "Manager,Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResponseId,RequestId,TextResponse")] Response response, int id)
        {
            response.RequestId = id;
            ModelState.Remove("Request");
            ModelState.Remove("RequestId");
            if (ModelState.IsValid)
            {
                _context.Add(response);
                await _context.SaveChangesAsync();
                var request = _context.Request.Find(id);
                return RedirectToAction("RequestsInProgress", new RouteValueDictionary(new
                {
                    Controller = "Manager",
                    Action = "RequestsInProgress",
                    id = request.ManagerId
                }));
            }
            ViewData["RequestId"] = new SelectList(_context.Request, "RequestId", "TextRequest", response.RequestId);
            return View(response);
        }

        [Authorize(Roles = "Admin")]
        // GET: Responses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Responses == null)
            {
                return NotFound();
            }
            var response = await _context.Responses
                 .Include(r => r.Request)
                 .FirstOrDefaultAsync(m => m.ResponseId == id);
            //var response = await _context.Responses.FindAsync(id);
            if (response == null)
            {
                return NotFound();
            }
            return View(response);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResponseId,RequestId,TextResponse")] Response response)
        {
            if (id != response.ResponseId)
            {
                return NotFound();
            }
            ModelState.Remove("Request");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(response);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResponseExists(response.ResponseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                var request = _context.Request.Find(id);
                return RedirectToAction("RequestsInProgress", new RouteValueDictionary(new
                {
                    Controller = "Manager",
                    Action = "RequestsInProgress",
                    id = request.ManagerId
                }));
            }
            return View(response);
        }

        [Authorize(Roles = "Admin")]
        // GET: Responses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Responses == null)
            {
                return NotFound();
            }

            var response = await _context.Responses
                .Include(r => r.Request)
                .FirstOrDefaultAsync(m => m.ResponseId == id);
            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Responses == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Responses'  is null.");
            }
            var response = await _context.Responses.FindAsync(id);
            if (response != null)
            {
                _context.Responses.Remove(response);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResponseExists(int id)
        {
          return (_context.Responses?.Any(e => e.ResponseId == id)).GetValueOrDefault();
        }
    }
}

Technical support/Views/Requests/Create.cshtml
@model Technical_support.ViewModel.RequestImage
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager


@{
    ViewData["Title"] = "Создать заявку";
}

<div class="pagetitle">
    <div class="header-h1">
        <h1>Создать заявку</h1>
    </div>
    <nav>
        <ol class="breadcrumb">
            @if (User.IsInRole("Admin"))
            {
                <li class="breadcrumb-item">
                    <a asp-controller="Admin"
                       asp-action="Index">Главная</a>
                </li>
            }
            else
            {
                if (User.IsInRole("Manager"))
                {
                    <li class="breadcrumb-item">
                        <a asp-controller="Manager"
                           asp-action="Index">Главная</a>
                    </li>
                }
                else
                {
                    <li class="breadcrumb-item">
                        <a asp-controller="Client"
                           asp-action="Index">Главная</a>
                    </li>
                }
            }
            <li class="breadcrumb-item">Заявки</li>
            <li class="breadcrumb-item active">Создать заявку</li>
        </ol>
    </nav>
</div>
<div class="cards">
    <div class="row">
        <div class="col-md-10">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" id="mypadding" hidden>
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" value="@UserManager.GetUserId(User)" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding">
                    <label asp-for="ThemeId" class="control-label">Тема заявки</label>
                    <select asp-for="ThemeId" class="form-select" asp-items="ViewBag.ThemeId"></select>
                </div>
                <div class="form-group" id="mypadding">
                    <label asp-for="PrioritetId" class="control-label">Приоритет</label>
                    <select asp-for="PrioritetId" class="form-select" asp-items="ViewBag.PrioritetId"></select>
                </div>
                <div class="form-group" id="mypadding">
                    <label asp-for="TextRequest" class="control-label"></label>
                    <textarea asp-for="TextRequest" class="form-control" id="biginput"></textarea>
                    <span asp-validation-for="TextRequest" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding">
                    <label asp-for="image" class="control-label"></label>
                    <input asp-for="image" class="form-control" />
                    <span asp-validation-for="image" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding" hidden>
                    <label asp-for="DateOpen" class="control-label"></label>
                    <input asp-for="DateOpen" class="form-control" />
                    <span asp-validation-for="DateOpen" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding" hidden>
                    <label asp-for="ManagerId" class="control-label"></label>
                    <input asp-for="ManagerId" class="form-control" />
                    <span asp-validation-for="ManagerId" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding" hidden>
                    <label asp-for="DateClose" class="control-label"></label>
                    <input asp-for="DateClose" class="form-control" />
                    <span asp-validation-for="DateClose" class="text-danger"></span>
                </div>
                <div class="form-group" id="mypadding" hidden>
                    <label asp-for="StatusRequestId" class="control-label"></label>
                    <select asp-for="StatusRequestId" class="form-control" asp-items="ViewBag.StatusRequestId"></select>
                </div>
                <div class="form-group" id="mypadding">
                    <input type="submit" value="Создать" class="btn btn-primary" />
                    <a asp-controller="Requests" asp-action="MyRequests" asp-route-id="@UserManager.GetUserId(User)"
                    class="btn btn-secondary">Назад</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Technical support/Views/Requests/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

@model Technical_support.ViewModel.RequestDetail

@{
    ViewData["Title"] = "Детали заявки";
}

<div class="pagetitle">
    <div class="header-h1">
        <h1>Детали заявки</h1>
    </div>
    <nav>
        <ol class="breadcrumb">
            @if (User.IsInRole("Admin"))
            {
                <li class="breadcrumb-item">
                    <a asp-controller="Admin"
                       asp-action="Index">Главная</a>
                </li>
            }
            else
            {
                if (User.IsInRole("Manager"))
                {
                    <li class="breadcrumb-item">
                        <a asp-controller="Manager"
                           asp-action="Index">Главная</a>
                    </li>
                }
                else
                {
                    <li class="breadcrumb-item">
                        <a asp-controller="Client"
                           asp-action="Index">Главная</a>
                    </li>
                }
            }
            <li class="breadcrumb-item">Заявки</li>
            <li class="breadcrumb-item active">Детали заявки</li>
        </ol>
    </nav>
</div>

<div class="cards2">
    <dl class="row" id="mypadding">
        <dt class="col-sm-4" id="mypadding">
            <a>Номер заявки</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.RequestId)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            <a>Имя пользователя</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.User.UserName)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            <a>Тема заявки</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.Theme.DescriptionTheme)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            <a>Приоритет заявки</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.Prioritet.PrioritetRequest)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            @Html.DisplayNameFor(model => model.Request.TextRequest)
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.TextRequest)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            @Html.DisplayNameFor(model => model.Request.File)
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @if (Model.Request.File != null)
            {
                <div id="image">
                    @Html.Raw("<img style='width:500px;' src=\"data:image/jpeg;base64,"
                + Convert.ToBase64String(Model.Request.File) + "\" />")
                </div>
                <div id="mypadding">
                    <button class="btn btn-primary btn-" id="btnclick">Увеличить</button>
                </div>
                <div id="photo" class="modal">
                    <div class="modal-dialog modal-sm"></div>
                    <div class="modal-content"></div>
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        @if (Model.Request.File != null)
                        {
                            @Html.Raw("<img src=\"data:image/jpeg;base64,"
                    + Convert.ToBase64String(Model.Request.File) + "\" />")
                        }
                        else
                        {
                            <a id="mypadding">-</a>
                        }
                    </div>
                </div>
            }
            else
            {
                <a id="mypadding">-</a>
            }
        </dd>
        <dt class="col-sm-4" id="mypadding">
            @Html.DisplayNameFor(model => model.Request.DateOpen)
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.DateOpen)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            <a>Менеджер</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.Manager.UserName)
        </dd>
        <dt class="col-sm-4" id="mypadding">
            @Html.DisplayNameFor(model => model.Request.DateClose)
        </dt>
        @if (Model.Request.DateClose == null)
        {
            <dd class="col-sm-8" id="mypadding">
                <a id="mypadding">-</a>
            </dd>
        }
        else
        {
            <dd class="col-sm-8" id="mypadding">
                @Html.DisplayFor(model => model.Request.DateClose)
            </dd>
        }
        <dt class="col-sm-4" id="mypadding">
            <a>Статус</a>
        </dt>
        <dd class="col-sm-8" id="mypadding">
            @Html.DisplayFor(model => model.Request.StatusRequest.Status)
        </dd>
        @if (Model.ListResponses.Count() == 0)
        {
            <dt class="col-sm-5 stroka1" id="mypadding">
                <a>Ответ на заявку</a>
            </dt>
            <dd class="col-sm-7 stroka2" id="mypadding">
                <i class="annul">На заявку пока нет ответа</i>
            </dd>
        }
        else
        {
            int count = 1;
            @foreach (var item in Model.ListResponses)
            {
                <dt class="col-sm-4 stroka1" id="mypadding">
                    <a id="mypadding2">Ответ № @count</a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-controller="Responses" asp-action="Edit" asp-route-id="@item.ResponseId"
                           class="btn btn-primary btn-sm" title="Изменить">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a asp-controller="Responses" asp-action="Delete" asp-route-id="@item.ResponseId"
                           class="btn btn-danger btn-sm" title="Удалить">
                            <i class="bi bi-trash"></i>
                        </a>
                    }
                </dt>
                <dd class="col-sm-8 stroka2" id="mypadding">
                    @item.TextResponse
                </dd>
                count++;
            }
        }
    </dl>
    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
    {
        <div id="mypadding">
            @if (Model.Request.StatusRequestId == 2)
            {
                <a asp-controller="Responses" asp-action="Create" asp-route-id="@Model.Request.RequestId"
                   class="btn btn-primary disabled">Ответить</a>
            }
            else
            {
                <a asp-controller="Responses" asp-action="Create" asp-route-id="@Model.Request.RequestId"
                   class="btn btn-primary">Ответить</a>
            }
            <a asp-controller="Manager" asp-action="ListRequests" class="btn btn-secondary">Назад</a>
        </div>
    }
    else
    {
        <div id="mypadding">
            @if (Model.Request.StatusRequest.Status == "Открыта")
            {
                <a asp-controller="Requests" asp-action="Edit" asp-route-id="@Model.Request.RequestId"
                   class="btn btn-primary">Изменить</a>
            }
            else
            {
                <a asp-controller="Requests" asp-action="Edit" asp-route-id="@Model.Request.RequestId"
                   class="btn btn-primary disabled" role="button" aria-disabled="true">Изменить</a>
            }
            <a asp-action="MyRequests" asp-route-id="@UserManager.GetUserId(User)"
               class="btn btn-secondary">Назад</a>
        </div>
    }
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnclick").click(function () {
            $("#photo").modal('show');
        });

        $("HidebtnModal").click(function () {
            $("#photo").modal('hide');
        });
    });
</script>