Technical support/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Technical_support.Data;
using Technical_support.Models;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace Technical_support.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private RoleManager<IdentityRole> roleManager;
        private UserManager<IdentityUser> userManager;
        public RoleController(RoleManager<IdentityRole> roleMgr, UserManager<IdentityUser> userMrg)
        {
            roleManager = roleMgr;
            userManager = userMrg;
        }

        public ViewResult Index() => View(roleManager.Roles);
        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }

        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nonMembers = new List<IdentityUser>();
            foreach (IdentityUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    IdentityUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    IdentityUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }
    }
}

Technical support/Controllers/ThemeRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Technical_support.Data;
using Technical_support.Models;

namespace Technical_support.Controllers
{
    public class ThemeRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ThemeRequestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ThemeRequests
        public async Task<IActionResult> Index()
        {
              return _context.ThemeRequests != null ? 
                          View(await _context.ThemeRequests.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ThemeRequests'  is null.");
        }

      
        // GET: ThemeRequests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ThemeRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ThemeId,NameTheme,DescriptionTheme")] ThemeRequest themeRequest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(themeRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(themeRequest);
        }

        // GET: ThemeRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ThemeRequests == null)
            {
                return NotFound();
            }

            var themeRequest = await _context.ThemeRequests.FindAsync(id);
            if (themeRequest == null)
            {
                return NotFound();
            }
            return View(themeRequest);
        }

        // POST: ThemeRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ThemeId,NameTheme,DescriptionTheme")] ThemeRequest themeRequest)
        {
            if (id != themeRequest.ThemeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(themeRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThemeRequestExists(themeRequest.ThemeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(themeRequest);
        }

        // GET: ThemeRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ThemeRequests == null)
            {
                return NotFound();
            }

            var themeRequest = await _context.ThemeRequests
                .FirstOrDefaultAsync(m => m.ThemeId == id);
            if (themeRequest == null)
            {
                return NotFound();
            }

            return View(themeRequest);
        }

        // POST: ThemeRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ThemeRequests == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ThemeRequests'  is null.");
            }
            var themeRequest = await _context.ThemeRequests.FindAsync(id);
            var requests = _context.Request
                           .Where(m => m.ThemeId == id);
            if (requests.Count() > 0)
            {
                ModelState.AddModelError(string.Empty, "Нельзя удалить тему с которой есть заявка");
                return View(themeRequest);
            }
            else 
            {
                if (themeRequest != null)
                {
                    _context.ThemeRequests.Remove(themeRequest);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
        }

        private bool ThemeRequestExists(int id)
        {
          return (_context.ThemeRequests?.Any(e => e.ThemeId == id)).GetValueOrDefault();
        }
    }
}

Technical support/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Technical_support.Data;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Technical_support.ViewModel;

namespace Technical_support.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private IPasswordHasher<IdentityUser> passwordHasher;

        public UserController(UserManager<IdentityUser> userMrg, IPasswordHasher<IdentityUser> passwordHash)
        {
            userManager = userMrg;
            passwordHasher = passwordHash;
        }

        public IActionResult Index()
        {
            return View(userManager.Users);
        }

        public IActionResult Create() => View();

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        // Метод для создания нового пользователя
        [HttpPost]
        public async Task<IActionResult> Create(CreateUser model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = new IdentityUser
                {
                    UserName = model.Name,
                    Email = model.Email,
                    NormalizedUserName = model.Email.ToUpper(),
                    EmailConfirmed = true
                };
                IdentityResult result = await userManager.CreateAsync(user, model.Password);
                string roleName = "Client";
                IdentityResult result1 = await userManager.AddToRoleAsync(user, roleName);
                if (result.Succeeded && result1.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    Errors(result);
                }
            }
            return View(model);
        }

        public IActionResult Update(string email)
        {
            return View();
        }

        // Метод для обновления данных пользователя
        [HttpPost]
        public async Task<IActionResult> Update(string id, string email, string password)
        {
            IdentityUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                if (!string.IsNullOrEmpty(email))
                    user.Email = email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(password))
                    user.PasswordHash = passwordHasher.HashPassword(user, password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }

        // Метод для удаления пользователя
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", userManager.Users);
        }
    }
}

Technical support/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Technical_support</title>
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/Technical_support.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/datatables.css" asp-append-version="true" />
</head>
<body>
    <header class="header fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-white box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Техническая поддержка</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex align-items-center justify-content-between">
                    <a href="#" class="logo d-flex align-items-center">
                        <img src="/img/logo.jpg" alt="">
                    </a>
                  @*   <i class="bi bi-list toggle-sidebar-btn"></i> *@
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav flex-grow-1">
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Client"))
    {
        <!-- ======= Sidebar ======= -->
        <aside id="sidebar" class="sidebar">

            <ul class="sidebar-nav" id="sidebar-nav">
                <!-- Личный кабинет -->
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-person"></i><span>Личный кабинет</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a asp-controller="Client"
                               asp-action="Profile" asp-route-id="@UserManager.GetUserId(User)">
                                <i class="bi bi-diamond-fill"></i><span>Информация</span>
                            </a>
                        </li>
                    </ul>
                </li><!-- конец Личный кабинет -->
                <!-- Заявки -->
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-journal-text"></i><span>Заявки</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        @if (User.IsInRole("Manager"))
                        {
                            <li>
                                <a asp-controller="Manager"
                                   asp-action="ListRequests">
                                    <i class="bi bi-diamond-fill"></i><span>Открытые заявки</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Manager"
                                   asp-action="CloseRequests" asp-route-id="@UserManager.GetUserId(User)">
                                    <i class="bi bi-diamond-fill"></i><span>Выполненные заявки</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Manager"
                                   asp-action="RequestsInProgress" asp-route-id="@UserManager.GetUserId(User)">
                                    <i class="bi bi-diamond-fill"></i><span>Заявки в работе</span>
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-controller="Admin"
                                   asp-action="ListRequests">
                                    <i class="bi bi-diamond-fill"></i><span>Cписок заявок</span>
                                </a>
                            </li>
                        }
                            <li>
                                <a asp-controller="Requests"
                                   asp-action="Create">
                                    <i class="bi bi-diamond-fill"></i><span>Создать заявку</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Requests"
                                   asp-action="MyRequests" asp-route-id="@UserManager.GetUserId(User)">
                                    <i class="bi bi-diamond-fill"></i><span>Мои заявки</span>
                                </a>
                            </li>
                    </ul>
                </li><!-- Конец Заявки -->
                <!-- Пользователи -->
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link collapsed" data-bs-target="#user-nav" data-bs-toggle="collapse" href="#">
                            <i class="bi bi-person-fill-check"></i><span>Пользователи</span><i class="bi bi-chevron-down ms-auto"></i>
                        </a>
                        <ul id="user-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                            <li>
                                <a asp-controller="Admin"
                                   asp-action="CreateUser">
                                    <i class="bi bi-diamond-fill"></i><span>Создать пользователя</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Admin"
                                   asp-action="Accounts">
                                    <i class="bi bi-diamond-fill"></i><span>Учетные записи</span>
                                </a>
                            </li>
                        </ul>
                    </li><!-- Конец Пользователи -->
                    <!-- Роли -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" data-bs-target="#role-nav" data-bs-toggle="collapse" href="#">
                            <i class="bi bi-clipboard2-pulse"></i><span>Роли</span><i class="bi bi-chevron-down ms-auto"></i>
                        </a>
                        <ul id="role-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                            <li>
                                <a asp-controller="Admin"
                                   asp-action="CreateRole">
                                    <i class="bi bi-diamond-fill"></i><span>Создать роль</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Admin"
                                   asp-action="AccountsRoles">
                                    <i class="bi bi-diamond-fill"></i><span>Управление ролями</span>
                                </a>
                            </li>
                        </ul>
                    </li><!-- Конец роли -->
                    <!-- Темы заявок -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" data-bs-target="#theme-nav" data-bs-toggle="collapse" href="#">
                            <i class="bi bi-card-list"></i><span>Темы заявок</span><i class="bi bi-chevron-down ms-auto"></i>
                        </a>
                        <ul id="theme-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                            <li>
                                <a asp-controller="ThemeRequests"
                                   asp-action="Create">
                                    <i class="bi bi-diamond-fill"></i><span>Создать тему</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="ThemeRequests"
                                   asp-action="Index">
                                    <i class="bi bi-diamond-fill"></i><span>Управление темами</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <!-- Конец Темы заявок -->
                }
            </ul>

        </aside>

        <!-- End Sidebar-->
    }
    <div class="container">
        <main role="main" id="main" class="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - Technical_support - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/dataTables.bootstrap5.js"></script>
    <script src="~/js/dataTables.js"></script>
    <script src="~/js/chart.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>